"""add source connection

Revision ID: 5aa998bb48f2
Revises: 4cff032f32e2
Create Date: 2026-06-11 21:49:27.890710

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5aa998bb48f2"
down_revision: Union[str, Sequence[str], None] = "4cff032f32e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_connection",
        sa.Column(
            "connector_name",
            sa.Enum("demo", "jira", "gitlab", name="connectorname"),
            nullable=False,
        ),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("selected_project_ids", sa.JSON(), nullable=False),
        sa.Column("selected_board_ids", sa.JSON(), nullable=False),
        sa.Column("selected_repository_ids", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("source_connection")
    # ### end Alembic commands ###
